name = "PhysicalUnits"
uuid = "260a1713-e24c-4a46-a881-35260f93c772"
authors = ["Alice loves Bob"]
version = "1.0.0-DEV"

[deps]
LocalRegistry = "89398ba2-070a-4b16-a995-9893c55d93cf"

[compat]
LocalRegistry = "0.5.7"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
